version: '2'
services:
    web:
      build: .
      restart: always
      container_name: facebook
      volumes:
       - .:/facebook
      depends_on:
       - mysql
      links:
       - mysql
      env_file:
       - .env
      expose:
       - 5001
      ports:
       - "5001:5001"
      command: /bin/bash -c "python run.py"
    mysql:
      container_name: facebook-mysql
      image: mysql:5.6
      ports:
       - 3306:3306
      environment:
       - MYSQL_ALLOW_EMPTY_PASSWORD=yes
       - MYSQL_DATABASE=facebook_local
